<a href="https://colab.research.google.com/github/samaasabri/Neural_Network/blob/main/NN2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [189]:
Input_layer=[1,1,1,1,1,1]
hidden_layers=3
neurons=[10,10,10]
activision=1
Target=[0,0,1]

In [190]:
import numpy as np

#Both parameters taken from GUI
#ex >>(3,[10,10,10])

def Intialize_weights(hidden_layers,neurons):
  wieght_matrices=[]
  for i in range(hidden_layers+1):
    w_i=[]
    if i==0:
      w_i=np.random.rand(neurons[i],6)
    elif i== hidden_layers:
      w_i=np.random.rand(3,neurons[i-1])
    else:
      w_i=np.random.rand(neurons[i],neurons[i-1])


    #print(w_i.shape)
    #print('----------------------------------------')
    wieght_matrices.append(w_i)

  return  wieght_matrices

wieght_matrices=Intialize_weights(hidden_layers,neurons)

# **Forward**

In [191]:
def feedForward(Input_layer,neurons,wieght_matrices,activision):
    #activison = 1 ---> sigmoid
    #activison = 0 ---> tengent
  neurons.append(3)
  #contains all f for each layer
  array_of_fs=[]

  def sigmoid(f_i):
    return 1/(1+np.exp(-f_i))

  def tengent(f_i):
    return np.tanh(f_i)

  for i in range(hidden_layers+1):

    #print("Layer: ",i)

    #f contains net value for wach neuron
    f=[]

    for n in range(neurons[i]):
      #print("Neuron: ",n)
      #print(wieght_matrices[i][n])

      if i==0:
        print("weights")
        print(wieght_matrices[i][n])
        print("input layer")
        print(Input_layer)
        f_i=np.dot(wieght_matrices[i][n],Input_layer)
        print(f_i)
        if activision:
            f_i = sigmoid(f_i)
        else:
            f_i = tengent(f_i)
        f.append(f_i)
      else:
        print("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh")
        print(array_of_fs[i-1])
        f_i=np.dot(wieght_matrices[i][n],array_of_fs[i-1])
        if activision:
            f_i = sigmoid(f_i)
        else:
            f_i = tengent(f_i)
        f.append(f_i)


    array_of_fs.append(f)
  return  array_of_fs


In [192]:
wieght_matrices=Intialize_weights(hidden_layers,neurons)
array_of_fs=feedForward(Input_layer,neurons,wieght_matrices,0)
print(array_of_fs)
print(wieght_matrices)

weights
[0.43845764 0.86112865 0.83008589 0.21982201 0.12567138 0.71376473]
input layer
[1, 1, 1, 1, 1, 1]
3.188930306541006
weights
[0.99664465 0.2050555  0.27017601 0.98035159 0.21342321 0.60397127]
input layer
[1, 1, 1, 1, 1, 1]
3.2696222306183493
weights
[0.22233551 0.25161669 0.6330376  0.35848104 0.46803945 0.60944163]
input layer
[1, 1, 1, 1, 1, 1]
2.542951915142387
weights
[0.08965906 0.68209052 0.75744177 0.25291216 0.64229476 0.18722838]
input layer
[1, 1, 1, 1, 1, 1]
2.6116266475330754
weights
[0.6562884  0.58000521 0.96936769 0.122741   0.74144849 0.13556495]
input layer
[1, 1, 1, 1, 1, 1]
3.2054157426948304
weights
[0.14988182 0.19958618 0.29389091 0.01311946 0.00918042 0.53090767]
input layer
[1, 1, 1, 1, 1, 1]
1.1965664600741621
weights
[0.42288895 0.05216016 0.12648179 0.33356804 0.03613591 0.96091287]
input layer
[1, 1, 1, 1, 1, 1]
1.9321477271519865
weights
[0.07507402 0.76643481 0.99980296 0.49904086 0.49209845 0.71209917]
input layer
[1, 1, 1, 1, 1, 1]
3.54455028027

# **BackPropagation**

In [193]:
def calc_weight_arr(arr_of_arrs,idx):
  arr_of_wights=[]
  for i in arr_of_arrs:
    arr_of_wights.append(i[idx])
  return arr_of_wights

In [194]:
def sigmoid_dash(f_i):
    return ((f_i)*(1-f_i))

def tengent_dash(f_i):
    return (1-pow(np.tanh(f_i),2))



In [195]:
def backPropagate(Target,neurons,wieght_matrices,activision,array_of_fs):

  array_of_errors=[]
  j=-1

  for i in range(hidden_layers,-1,-1):
    # print("Layer:" ,i)
    error=[]

    for n in range(neurons[i]):
      # print("Neuron: ",n)
    #check activision function
      if activision:
        dash = sigmoid_dash(array_of_fs[i][n])

        if i==hidden_layers:
          # print('Target:  ',Target[n])
          error_i=(Target[n]- array_of_fs[i][n])*dash

        else:
          #print("Array of errors: ",array_of_errors[j])
          # print("Weight matrix: ",wieght_matrices[i][n])
          wights=calc_weight_arr(wieght_matrices[i+1],n)
          # print("Weight matrix:",wights)
          # print("N is : ",n)

          error_i= np.dot(wights,array_of_errors[j]) *dash
         #continue


      else:
          error_i = tengent_dash(array_of_fs[i][n])

      error.append(error_i)
      #print(error)
      #print(array_of_fs[i][n])

    array_of_errors.append(error)
    print("Array of errors: ",array_of_errors)
    print("----------------")
    j+=1
  return array_of_errors


In [196]:
array_of_errors=backPropagate(Target,neurons,wieght_matrices,activision,array_of_fs)

Array of errors:  [[-0.000382529264592193, -1.8956344531696358e-05, 2.819202693854097e-07]]
----------------
Array of errors:  [[-0.000382529264592193, -1.8956344531696358e-05, 2.819202693854097e-07], [-3.837995280286467e-09, -1.5805719646620616e-07, -6.510689403510183e-08, -2.0235011991339574e-08, -5.292546456184449e-08, -5.189238933219364e-09, -5.935115022083241e-10, -1.391265407284485e-10, -2.2922770289218446e-08, -1.1958852650992493e-06]]
----------------
Array of errors:  [[-0.000382529264592193, -1.8956344531696358e-05, 2.819202693854097e-07], [-3.837995280286467e-09, -1.5805719646620616e-07, -6.510689403510183e-08, -2.0235011991339574e-08, -5.292546456184449e-08, -5.189238933219364e-09, -5.935115022083241e-10, -1.391265407284485e-10, -2.2922770289218446e-08, -1.1958852650992493e-06], [-7.789160136202476e-10, -1.173679720766596e-10, -1.6294364416703266e-11, -5.3019911480408756e-12, -7.781298817801101e-10, -2.5685403581561062e-11, -2.5540200980992762e-11, -1.2708820003887508e-10, 

#**Update weights**

In [197]:
array_of_errors.reverse()
# print(array_of_errors)

In [198]:
def Update_wieghts(array_of_errors,wieght_matrices,Input_layer,learning_rate,hidden_layers,neurons,array_of_fs):

  for i in range(hidden_layers+1):
    #print("Layer: ",i)


    for n in range(neurons[i]):
      #print("Neuron: ",n)
      #print(wieght_matrices[i][n])
      for j in range(len(wieght_matrices[i][n])):


         if i==0:
           wieght_matrices[i][n][j]=wieght_matrices[i][n][j]+learning_rate*array_of_errors[i][n]*Input_layer[j]

         else:
           wieght_matrices[i][n][j]=wieght_matrices[i][n][j]+learning_rate*array_of_errors[i][n]*array_of_fs[i][n]


  return wieght_matrices




In [199]:
updated_weights=Update_wieghts(array_of_errors,wieght_matrices,Input_layer,0.1,hidden_layers,neurons,array_of_fs)
updated_weights

[array([[0.43845764, 0.86112865, 0.83008589, 0.21982201, 0.12567138,
         0.71376473],
        [0.99664465, 0.2050555 , 0.27017601, 0.98035159, 0.21342321,
         0.60397127],
        [0.22233551, 0.25161669, 0.6330376 , 0.35848104, 0.46803945,
         0.60944163],
        [0.08965906, 0.68209052, 0.75744177, 0.25291216, 0.64229476,
         0.18722838],
        [0.6562884 , 0.58000521, 0.96936769, 0.122741  , 0.74144849,
         0.13556495],
        [0.14988182, 0.19958618, 0.29389091, 0.01311946, 0.00918042,
         0.53090767],
        [0.42288895, 0.05216016, 0.12648179, 0.33356804, 0.03613591,
         0.96091287],
        [0.07507402, 0.76643481, 0.99980296, 0.49904086, 0.49209845,
         0.71209917],
        [0.41947563, 0.89488748, 0.7620771 , 0.84511771, 0.30269114,
         0.11727004],
        [0.9476989 , 0.76907477, 0.0321587 , 0.24855638, 0.57814126,
         0.58505767]]),
 array([[0.0401881 , 0.58438772, 0.45943911, 0.87619122, 0.0467109 ,
         0.57689172

In [200]:
def train(Input,target,hidden_layers_num,neurons_num,Activation_used,learninR,num_epochs):
  # print("ssssssssssssssssssssssssss")
  # print(Input[0])
  # print(target[0][0])
  # print(type(Input[0]))
  # print(type(target[0]))
  net=Intialize_weights(hidden_layers=hidden_layers_num,neurons=neurons_num)
  for i in range(num_epochs):
    for j in range(len(Input)):
      FF=feedForward(Input[j],neurons_num,net,Activation_used)
      array_of_error=backPropagate(target[j][0],neurons_num,net,Activation_used,FF)
      array_of_error.reverse()
      net=Update_wieghts(array_of_error,net,Input[j],learninR,hidden_layers_num,neurons_num,FF)

  return net




In [201]:
def predict(input,neurons_num,net,Activation_used):
  predictions=[]
  for sample in input:
    FF=feedForward(sample,neurons_num,net,Activation_used)
    print(FF[-1])
    predictions.append(np.argmax(FF[-1]))

  return predictions


In [202]:
import pandas as pd
import numpy as np


In [203]:
data = pd.read_excel("/content/Dry_Bean_Dataset.xlsx")

data['MinorAxisLength'].fillna(value=data['MinorAxisLength'].mean(), inplace=True)

In [204]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             150 non-null    int64  
 1   Perimeter        150 non-null    float64
 2   MajorAxisLength  150 non-null    float64
 3   MinorAxisLength  150 non-null    float64
 4   roundnes         150 non-null    float64
 5   Class            150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [205]:
def encode(x):
  res=np.zeros((1,3))
  if x=='BOMBAY':
    res[0][0]=1
  elif x=='CALI':
    res[0][1]=1
  else:
    res[0][2]=1

  return res.tolist()


In [206]:
def normalization(data):

  data = (data - data.min()) / (data.max() - data.min()) * (10-1) - 1
  print(str(data.min())+" "+str( data.max()))
  return data, data.min(), data.max()


def normalization_test(data,dMin,dMax):
  data = (data - dMin) / (dMax - dMin) * (10-1) - 1
  print(str(dMin)+" "+str(dMax))
  return data

In [207]:
from sklearn.preprocessing import StandardScaler


In [210]:
def preprocess(data):

    scaler = StandardScaler()

    d1 = data.iloc[:30, :]
    d2 = data.iloc[50:80, :]
    d3 = data.iloc[100:130,:]
    d = pd.concat([d1, d2])
    df= pd.concat([d, d3])
    df=df.sample(frac=1)
    #   x_train,DMIN,DMAX=normalization(df.iloc[:,:-1])
    df1 = df.iloc[:,:-1]
    df1["X1"] = 1
    model = scaler.fit(df1)
    df1 = model.transform(df1)
    x_train=df1.tolist()

    y_train=[]
    for i in df['Class']:
        y_train.append(encode(i))

    d1 = data.iloc[30:50, :]
    d2 = data.iloc[80:100, :]
    d3 = data.iloc[130:,:]
    d = pd.concat([d1, d2])
    df= pd.concat([d, d3])
    df=df.sample(frac=1)

    #   x_test=normalization_test(df.iloc[:,:-1],DMIN,DMAX)
    #   print(x_test)



    df2 = df.iloc[:,:-1]
    df2["X1"] = 1
    df2 = model.transform(df2)
    x_test=df2.tolist()
    y_test=[]
    for i in df['Class']:
        y_test.append(encode(i))
    print(x_train)
    print("------------------------------------------------------------------------------------")
    print(x_test)

    print(df1.shape)
    print(df2.shape)

    return x_train,x_test,y_train,y_test
#   print(len(x_train))
#   print(len(x_test))
#   print(len(y_train))
#   print(len(y_test))



#   print(y_train)
#   print(y_test)


In [211]:
x_train,x_test,y_train,y_test = preprocess(data)


[[1.5018141014992898, 1.4199281052853123, 1.397937279862326, 1.489407249655315, 0.3633122078996488, 0.0], [-0.9492241487866484, -1.0976256805119027, -1.2531928269544783, -0.7941056703435988, 1.2605796121229522, 0.0], [1.4849291558256528, 1.4968983124822737, 1.4850591005449847, 1.3976658856315773, -0.509611977574216, 0.0], [1.3658740085758618, 1.212961463636121, 1.1698412387451544, 1.488523597086426, 1.457641934846318, 0.0], [1.3772701840305204, 1.3431516644000179, 1.2922778858542074, 1.397345747373013, 0.184318283257486, 0.0], [-0.3786246210221689, -0.2209230831496635, -0.020262515612484263, -0.46347754137088776, -0.7844657202481439, 0.0], [-0.44167570603763734, -0.2959625474553732, -0.10635233686250607, -0.5370817391123884, -0.8018309418599293, 0.0], [-0.387322926369194, -0.2839628765828598, -0.08953552291443824, -0.4394871184873798, -0.0048341741905116135, 0.0], [-0.9351533607252842, -1.0220879599761927, -0.9499958040835963, -1.0464742833495375, 0.13521402994983597, 0.0], [-0.3963933

In [212]:
neurons = [12,6,3]
net = train(x_train,y_train,3,neurons,1,0.01,100)

Streaming output truncated to the last 5000 lines.
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
[0.2829478313910921, 0.3583759624275068, 0.40500018085733613, 0.35081793480700657, 0.3755256167315103, 0.3608002580859106, 0.3440574859006934, 0.3755025796116501, 0.36371883420133094, 0.3781974466660006, 0.3796445277859536, 0.3858303761676742]
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
[0.2829478313910921, 0.3583759624275068, 0.40500018085733613, 0.35081793480700657, 0.3755256167315103, 0.3608002580859106, 0.3440574859006934, 0.3755025796116501, 0.36371883420133094, 0.3781974466660006, 0.3796445277859536, 0.3858303761676742]
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
[0.2829478313910921, 0.3583759624275068, 0.40500018085733613, 0.35081793480700657, 0.3755256167315103, 0.3608002580859106, 0.3440574859006934, 0.3755025796116501, 0.36371883420133094, 0.3781974466660006, 0.3796445277859536, 0.3858303761676742]
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
[0.2829478313910921, 0.3583759624275068, 0.40

In [213]:
preds=predict(x_test,neurons,net,1)

Streaming output truncated to the last 5000 lines.
weights
[0.06887474 0.94955101 0.50039064 0.62435619 0.97770978 0.90387566]
input layer
[-0.8890569938862364, -0.9309416710131729, -0.9249991811573567, -0.9263109162066346, -0.27648557947450336, 0.0]
-2.256741712671827
weights
[0.45891209 0.52135126 0.67157376 0.22086971 0.32959648 0.12245473]
input layer
[-0.8890569938862364, -0.9309416710131729, -0.9249991811573567, -0.9263109162066346, -0.27648557947450336, 0.0]
-1.8102744844974101
weights
[0.79198704 0.17748606 0.90086363 0.20760725 0.514562   0.80198902]
input layer
[-0.8890569938862364, -0.9309416710131729, -0.9249991811573567, -0.9263109162066346, -0.27648557947450336, 0.0]
-2.037226732797182
weights
[0.17770186 0.91391628 0.13801441 0.79341611 0.36287239 0.5070203 ]
input layer
[-0.8890569938862364, -0.9309416710131729, -0.9249991811573567, -0.9263109162066346, -0.27648557947450336, 0.0]
-1.9717320287457574
weights
[0.24257332 0.70898024 0.23858119 0.46430556 0.48830898 0.04207

In [214]:
preds

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [ ]:
# from sklearn.metrics import confusion_matrix

# # confusion_matrix funnction a matrix containing the summary of predictions
# print(confusion_matrix(y_test, predictions))